---
# tasks file for monitor_cluster

- name : Get cluster status during installation
  crucible.ocm.rest_api_call:
    method: "GET"
    query: None
    url_endpoint: { 
                    #"host": "" for on-prem installation specify installer host dns
                    #"port": "" for on-prem install specify installer port 
                    "api_version": "v1" 
                    "api_endpoint": "clusters/{{ CLUSTER_ID }}"

                  }
    authentication: { 
                      ##include api_token if use cloud installer 
                      "username": "{{ HTTP_AUTH_USERNAME }}", 
                      "password": "{{ HTTP_AUTH_PASSWORD }}", 
                      "api_token": "{{ HTTP_API_TOKEN }}" 
                    }
    status_code: [200, 201]
    return_content: True
  register: cluster
  delegate_to: bastion

- name: Identify the host
  set_fact:
    current_host: "{{ item }}"
  loop: "{{ cluster.json.hosts }}"
  when: item.requested_hostname == inventory_hostname
  no_log: True

- name: Start host monitoring
  include_tasks: hosts_monitoring.yml
  args:
    apply:
      delegate_to: bastion
  vars:
    host_id: "{{ current_host.id }}"
    host_name: "{{ current_host.requested_hostname }}"
  no_log: True
