---
# tasks file for install_cluster/hosts_discovery

- name: "Wait for up to 10 minutes for node discovery - {{ discovered_host.id }}"
  crucible.ocm.rest_api_call:
    method: "PATCH"
    query: None
    url_endpoint: { 
                    #"host": "" for on-prem installation specify installer host dns
                    #"port": "" for on-prem install specify installer port 
                    "api_version": "v1" 
                    "api_endpoint": "clusters"

                  }
    authentication: { 
                      ##include api_token if use cloud installer 
                      "username": "{{ HTTP_AUTH_USERNAME }}", 
                      "password": "{{ HTTP_AUTH_PASSWORD }}", 
                      "api_token": "{{ HTTP_API_TOKEN }}" 
                    }
  register: host
  until: host.json.inventory is defined
  retries: 10
  delay: 60
  when: discovered_host.inventory is not defined

- name: Identify the discovered host {{ discovered_host.id }}
  set_fact:
    host: "{{ host.json }}"
  when: discovered_host.inventory is not defined

- name: Identify the discovered host {{ discovered_host.id }}
  set_fact:
    host: "{{ discovered_host }}"
  when: discovered_host.inventory is defined

- name: Identify the host {{ host.id }} properties
  set_fact:
    host_inventory: "{{ host.inventory }}"
    host_id: "{{ host.id }}"
    host_name: "{{ host.requested_hostname | default('node' + lookup('password', '/dev/null chars=ascii_lowercase,digits length=8')) }}"
    host_role: "auto-assign"

- name: Identify the host {{ host.id }} interfaces
  set_fact:
   host_interfaces: "{{ host_inventory.interfaces }}"

- name : Set host name and role for {{ host.id }}
  set_fact:
    host_name: "{{ item.0 }}"
    host_role: "{{ hostvars[item.0]['role'] }}"
  when: hostvars[item.0]['mac'] is defined and ( hostvars[item.0]['mac'] | upper ) == ( item.1.mac_address | upper )
  loop: "{{ inventory_nodes | product(host_interfaces) | list }}"
  no_log: True

- name : Prepare hosts name and role for {{ host_name }}
  set_fact:
    host:
      id: "{{ host_id }}"
      hostname: "{{ host_name }}"
      role: "{{ host_role }}"
  when: host_name is defined or host_role is defined

- name: Set host name and role for {{ host_name }}
  crucible.ocm.rest_api_call:
    method: "PATCH"
    query: None
    url_endpoint: { 
                    #"host": "" for on-prem installation specify installer host dns
                    #"port": "" for on-prem install specify installer port 
                    "api_version": "v1" 
                    "api_endpoint": "clusters"

                  }
    authentication: { 
                      ##include api_token if use cloud installer 
                      "username": "{{ HTTP_AUTH_USERNAME }}", 
                      "password": "{{ HTTP_AUTH_PASSWORD }}", 
                      "api_token": "{{ HTTP_API_TOKEN }}" 
                    }
    status_code: [201]
    return_content: True
    body: {
        "hosts_names": [ "{{ host }}" ],
        "hosts_roles": [ "{{ host }}" ]
    }
  register: http_reply

- name: Set the installation disk path
  when: hostvars[host_name]['installation_disk_path'] is defined
  block:
    - name: Fetch the installation disk path from host vars
      set_fact:
        installation_disk_path: "{{ hostvars[host_name]['installation_disk_path'] }}"

    - name: "Set the installation disk to {{ installation_disk_path }} for {{ host_name }}"
      crucible.ocm.rest_api_call:
        method: "PATCH"
        query: None
        url_endpoint: { 
                        #"host": "" for on-prem installation specify installer host dns
                        #"port": "" for on-prem install specify installer port 
                        "api_version": "v1" 
                        "api_endpoint": "clusters"

                      }
        authentication: { 
                          ##include api_token if use cloud installer 
                          "username": "{{ HTTP_AUTH_USERNAME }}", 
                          "password": "{{ HTTP_AUTH_PASSWORD }}", 
                          "api_token": "{{ HTTP_API_TOKEN }}" 
                        }
        body: {
          "disks_selected_config": [
            {
              "id": "{{ host_id }}",
              "disks_config": [
                {
                  "id": "{{ installation_disk_path }}",
                  "role": "install"
                }
              ]
            }
          ]
        }
      register: http_reply
